package desafio.ejb.manager;


/*
  ** This file was automatically generated by EJBGen 2.16
  ** Build: 20050706-1110
*/


import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import javax.ejb.FinderException;
import java.rmi.RemoteException;
import java.util.Collection;

// BEGIN imports from bean class
import desafio.ProdutoCategoriaProdutoVO;
import desafio.CategoriaProdutoVO;
import desafio.ejb.geral.CategoriaProduto;
import desafio.ejb.geral.CategoriaProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProduto;
import desafio.ejb.geral.ProdutoCategoriaProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProdutoBeanPK;
import desafio.ejb.geral.ProdutoCategoriaProdutoHome;
import desafio.ejb.geral.CategoriaProdutoHome;
import desafio.infra.DesafioException;
import itaipu.util.ServiceLocator;
import javax.naming.NamingException;
import javax.ejb.*;
import weblogic.ejb.*;
// END imports from bean class


public interface CategoriaProdutoSessionHome extends EJBHome {



  public CategoriaProdutoSessionRemote create()     throws CreateException, RemoteException;



}
