package desafio.ejb.manager;


/*
  ** This file was automatically generated by EJBGen 2.16
  ** Build: 20050706-1110
*/


import javax.ejb.EJBObject;
import java.rmi.RemoteException;

// BEGIN imports from bean class
import desafio.ProdutoCategoriaProdutoVO;
import desafio.CategoriaProdutoVO;
import desafio.ejb.geral.CategoriaProduto;
import desafio.ejb.geral.CategoriaProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProduto;
import desafio.ejb.geral.ProdutoCategoriaProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProdutoBeanPK;
import desafio.ejb.geral.ProdutoCategoriaProdutoHome;
import desafio.ejb.geral.CategoriaProdutoHome;
import desafio.infra.DesafioException;
import itaipu.util.ServiceLocator;
import javax.naming.NamingException;
import javax.ejb.*;
import weblogic.ejb.*;
// END imports from bean class


public interface CategoriaProdutoSessionRemote extends EJBObject {


  /**
   * Método responsável por inserir na lista de CategoriaProduto
   * @param produtoCategoriaProdutoVO - categoriaProdutoVO
   * @return CategoriaProdutoVO
   * @throws DesafioException
   */
  public desafio.CategoriaProdutoVO addProdutoCategoriaProduto(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO, desafio.CategoriaProdutoVO categoriaProdutoVO)     throws RemoteException, desafio.infra.DesafioException;

  /**
   * @param categoriaProdutoVO
   * @return CategoriaProdutoVO
   * @throws DesafioException
   */
  public desafio.CategoriaProdutoVO atualizarCategoriaProduto(desafio.CategoriaProdutoVO categoriaProdutoVO)     throws RemoteException, desafio.infra.DesafioException;

  /**
   * M�todo responsável por excluir da lista de CategoriaProduto
   * @param produtoCategoriaProdutoVO - categoriaProdutoVO
   * @return CategoriaProdutoVO
   * @throws DesafioException
   */
  public void delProdutoCategoriaProduto(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO, desafio.CategoriaProdutoVO categoriaProdutoVO)     throws RemoteException, desafio.infra.DesafioException;
  public void eliminarCategoriaProduto(desafio.CategoriaProdutoVO categoriaProdutoVO)     throws RemoteException, desafio.infra.DesafioException;
  public desafio.CategoriaProdutoVO obterCategoriaProduto(desafio.CategoriaProdutoVO categoriaProdutoVO)     throws RemoteException, desafio.infra.DesafioException;

}
