package desafio.ejb.manager;


/*
  ** This file was automatically generated by EJBGen 2.16
  ** Build: 20050706-1110
*/


import javax.ejb.EJBObject;
import java.rmi.RemoteException;

// BEGIN imports from bean class
import desafio.ProdutoCategoriaProdutoVO;
import desafio.ProdutoVO;
import desafio.ejb.geral.Produto;
import desafio.ejb.geral.ProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProduto;
import desafio.ejb.geral.ProdutoCategoriaProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProdutoBeanPK;
import desafio.ejb.geral.ProdutoCategoriaProdutoHome;
import desafio.ejb.geral.ProdutoHome;
import desafio.infra.DesafioException;
import itaipu.util.ServiceLocator;
import javax.naming.NamingException;
import javax.ejb.*;
import weblogic.ejb.*;
// END imports from bean class


public interface ProdutoSessionRemote extends EJBObject {


  /**
   * Método responsável por inserir na lista de Produto
   * @param produtoCategoriaProdutoVO
            - produtoVO
   * @return ProdutoVO
   * @throws DesafioException
   */
  public desafio.ProdutoVO addProdutoCategoriaProduto(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO, desafio.ProdutoVO produtoVO)     throws RemoteException, desafio.infra.DesafioException;

  /**
   * Método atualiza os dados primitivos do objeto
   * @param produtoVO
   * @return ProdutoVO
   * @throws DesafioException
   */
  public desafio.ProdutoVO atualizarProduto(desafio.ProdutoVO produtoVO)     throws RemoteException, desafio.infra.DesafioException;

  /**
   * M�todo responsável por excluir da lista de Produto
   * @param produtoCategoriaProdutoVO
            - produtoVO
   * @return ProdutoVO
   * @throws DesafioException
   */
  public void delProdutoCategoriaProduto(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO, desafio.ProdutoVO produtoVO)     throws RemoteException, desafio.infra.DesafioException;

  /**
   * Método exclui o objeto da persistência
   */
  public void eliminarProduto(desafio.ProdutoVO produtoVO)     throws RemoteException, desafio.infra.DesafioException;

  /**
   * Método obtém os dados primitivos do objeto
   */
  public desafio.ProdutoVO obterProduto(desafio.ProdutoVO produtoVO)     throws RemoteException, desafio.infra.DesafioException;

}
