package desafio.ejb.manager;


/*
  ** This file was automatically generated by EJBGen 2.16
  ** Build: 20050706-1110
*/


import javax.ejb.EJBObject;
import java.rmi.RemoteException;

// BEGIN imports from bean class
import desafio.CategoriaProdutoVO;
import desafio.ProdutoCategoriaProdutoVO;
import desafio.ProdutoVO;
import desafio.ejb.geral.CategoriaProduto;
import desafio.ejb.geral.CategoriaProdutoBean;
import desafio.ejb.geral.CategoriaProdutoHome;
import desafio.ejb.geral.Produto;
import desafio.ejb.geral.ProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProduto;
import desafio.ejb.geral.ProdutoCategoriaProdutoBean;
import desafio.ejb.geral.ProdutoCategoriaProdutoBeanPK;
import desafio.ejb.geral.ProdutoCategoriaProdutoHome;
import desafio.ejb.geral.ProdutoHome;
import desafio.infra.DesafioException;
import itaipu.util.ServiceLocator;
import javax.naming.NamingException;
import javax.ejb.*;
import weblogic.ejb.*;
// END imports from bean class


public interface ProdutoCategoriaProdutoSessionRemote extends EJBObject {

  public void eliminarProdutoCategoriaProduto(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO)     throws RemoteException, desafio.infra.DesafioException;
  public desafio.ProdutoCategoriaProdutoVO obterProdutoCategoriaProduto(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO)     throws RemoteException, desafio.infra.DesafioException;

}
