package desafio.ejb.geral;


/*
  ** This file was automatically generated by EJBGen 2.16
  ** Build: 20050706-1110
*/


import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;
import javax.ejb.FinderException;
import java.rmi.RemoteException;
import java.util.Collection;

// BEGIN imports from bean class
import desafio.CategoriaProdutoVO;
import desafio.ProdutoCategoriaProdutoVO;
import desafio.infra.DesafioException;
import itaipu.util.ServiceLocator;
import java.util.Collection;
import javax.ejb.CreateException;
import javax.naming.NamingException;
import weblogic.ejb.GenericEntityBean;
// END imports from bean class


public interface CategoriaProdutoHome extends EJBLocalHome {

  public CategoriaProduto findByPrimaryKey(Long primaryKey)  throws FinderException;
;



  public CategoriaProduto create(desafio.CategoriaProdutoVO categoriaProdutoVO, desafio.ejb.geral.CategoriaProduto categoriaPai)     throws CreateException, desafio.infra.DesafioException;



}
