package desafio.ejb.geral;


/*
  ** This file was automatically generated by EJBGen 2.16
  ** Build: 20050706-1110
*/


import javax.ejb.EJBLocalObject;

// BEGIN imports from bean class
import desafio.CategoriaProdutoVO;
import desafio.ProdutoCategoriaProdutoVO;
import desafio.ProdutoVO;
import desafio.infra.DesafioException;
import itaipu.util.ServiceLocator;
import java.util.Collection;
import javax.ejb.CreateException;
import javax.naming.NamingException;
import weblogic.ejb.GenericEntityBean;
// END imports from bean class


public interface ProdutoCategoriaProduto extends EJBLocalObject {

  public desafio.ejb.geral.CategoriaProduto getCategoriaProduto() ;
  /**
   * Método obtem os dados do Bean para o VO
   * @return ProdutoCategoriaProdutoVO
   * @throws DesafioException
   */
  public desafio.ProdutoCategoriaProdutoVO getData()  throws desafio.infra.DesafioException;  public Long getId_categoria_produto() ;  public Long getId_produto() ;  public desafio.ejb.geral.Produto getProduto() ;  public void setCategoriaProduto(desafio.ejb.geral.CategoriaProduto arg) ;
  /**
   * M�todo seta os dados do VO para bean
   * @param produtoCategoriaProdutoVO
   * @throws DesafioException
   */
  public void setData(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO)  throws desafio.infra.DesafioException;  public void setId_categoria_produto(Long val) ;  public void setId_produto(Long val) ;  public void setProduto(desafio.ejb.geral.Produto arg) ;
  /**
   * Método valida os dados do Value Object
   * @param Produto com os dados a serem validados
   * @throws DesafioException
   */
  public void validaProdutoCategoriaProduto(desafio.ProdutoCategoriaProdutoVO produtoCategoriaProdutoVO)  throws desafio.infra.DesafioException;
}
