package desafio.ejb.geral;


/*
  ** This file was automatically generated by EJBGen 2.16
  ** Build: 20050706-1110
*/


import javax.ejb.EJBLocalObject;

// BEGIN imports from bean class
import desafio.ProdutoVO;
import desafio.infra.DesafioException;
import itaipu.util.ServiceLocator;
import java.util.Collection;
import javax.ejb.CreateException;
import javax.naming.NamingException;
import weblogic.ejb.GenericEntityBean;
// END imports from bean class


public interface Produto extends EJBLocalObject {


  /**
   * Método obtem os dados do Bean para o VO
   * @return ProdutoVO
   * @throws DesafioException
   */
  public desafio.ProdutoVO getData()  throws desafio.infra.DesafioException;  public Long getId_produto() ;  public String getNome_produto() ;
  /**
   * M�todo seta os dados do VO para bean
   * @param ProdutoVO
   * @throws DesafioException
   */
  public void setData(desafio.ProdutoVO produtoVO)  throws desafio.infra.DesafioException;  public void setId_produto(Long val) ;  public void setNome_produto(String val) ;
  /**
   * Método valida os dados do Value Object
   * @param Produto com os dados a serem validados
   * @throws DesafioException
   */
  public void validaProduto(desafio.ProdutoVO produtoVO)  throws desafio.infra.DesafioException;
}
